const INCREMENTED = "INCREMENTED";
const DECREMENTED = "DECREMENTED";
const OPEN_SIDEBAR ="OPEN_SIDEBAR";
const CLOSE_SIDEBAR= "CLOSE_SIDEBAR";




export { INCREMENTED, DECREMENTED, OPEN_SIDEBAR, CLOSE_SIDEBAR }