const INCREMENTED = "INCREMENTED";
const DECREMENTED = "DECREMENTED";
const OPEN_SIDEBAR ="OPEN_SIDEBAR";
const CLOSE_SIDEBAR= "CLOSE_SIDEBAR";
const GET_ALL_POSTS="GET_ALL_POSTS";


export { INCREMENTED, DECREMENTED, OPEN_SIDEBAR, CLOSE_SIDEBAR, GET_ALL_POSTS }