const TELEGRAM_CHANNELS = [
  { city: 'آذربایجان غربی', link: 't.me/eshelappwaz' },
  { city: 'آذربایجان شرقی', link: 't.me/eshelappeaz' },
  { city: 'اردبیل', link: 't.me/ashelappard' },
  { city: 'گیلان', link: 't.me/eshelappgil' },
  { city: 'مازندران', link: 't.me/eshelappmaz' },
  { city: 'گلستان', link: 't.me/eshelappgol' },
  { city: 'خراسان شمالی', link: 't.me/eshelappnkho' },
  { city: 'خراسان رضوی', link: 't.me/eshelappkhor' },
  { city: 'خراسان جنوبی', link: 't.me/eshelappskho' },
  { city: 'سمنان', link: 't.me/eshelappsem' },
  { city: 'تهران', link: 't.me/eselappteh' },
  { city: 'البرز', link: 't.me/eshelappalb' },
  { city: 'قزوین', link: 't.me/eshrlappqaz' },
  { city: 'زنجان', link: 't.me/eshelappzan' },
  { city: 'کردستان', link: 't.me/eshelappkor' },
  { city: 'کرمانشاه', link: 't.me/eshelappker' },
  { city: 'همدان', link: 't.me/eshelappham' },
  { city: 'مرکزی', link: 't.me/eshelappmar' },
  { city: 'قم', link: 't.me/eshelappqom' },
  { city: 'اصفهان', link: 't.me/eshelappesf' },
  { city: 'یزد', link: 't.me/eshelappyaz' },
  { city: 'چهار محال و بختیاری', link: 't.me/eshelappcha' },
  { city: 'لرستان', link: 't.me/eshelapplor' },
  { city: 'ایلام', link: 't.me/eshelappela' },
  { city: 'خوزستان', link: 't.me/eshelappkhu' },
  { city: 'کهگیلویه و بویر احمد', link: 't.me/eshelappkoh' },
  { city: 'فارس', link: 't.me/eshelappfar' },
  { city: 'کرمان', link: 't.me/eshelappkerm' },
  { city: 'سیستان و بلوچستان', link: 't.me/eshelappsis' },
  { city: 'هرمزگان', link: 't.me/eshelapphor' },
  { city: 'بوشهر', link: 't.me/eshelappbus' },
];

export { TELEGRAM_CHANNELS };